title: "Resource Manager OpenAPI Stack"
description: "This stack provides the basic terraform modules to help developers manager APIs on Oracle Cloud Infrastructure"
stackDescription: "A stack to manage APIs in Oracle Cloud Infrastructure"
informationalText: "The Pet Store Demo is so cool, that I want to develop more stacks on OCI"
schemaVersion: 1.1.0
version: "20200301"
logoUrl: https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/grri30nzv1ul/b/public/o/OpenAPI-Logo.png
variableGroups:
    - title: "Required Inputs"
    - variables:
        - "region"
        - "compartment_ocid"
        - "vcn_ocid"
        - "subnet_ocid"
variables:
    "region":
        type: oci:identity:region:name
        visible: true
        required: true
        title: "Region"
        description: "The region to run this stack"  
    "compartment_ocid":
        type: oci:identity:compartment:id
        visible: true
        required: true
        title: "Compartment"
        description: "The compartment to create the resources"
    "vcn_ocid":
        type: oci:core:vcn:id
        visible: true
        required: true
        title: "VCN"
        description: "The VCN to create the resources"
        dependsOn:
            compartmentId: compartment_ocid
    "subnet_ocid":
        type: oci:core:subnet:id
        visible: true
        required: true
        title: "Subnet"
        description: "the subnet to create the API Gateway for the deployment of the APIs"
        dependsOn:
            compartmentId: compartment_ocid
            vcnId: vcn_ocid
outputs:
    oci_gateway_ocid:
        type: ocid
        visible: true
    oci_gateway_hostname:
        type: string
        visible: true
    oci_gateway_endpoint_type:
        type: string
        visible: true
    oci_gateway_display_name:
        type: string
        visible: true
    api_resource_ocid:
        type: ocid
        visible: true
    api_resource_specification_type:
        type: string
        visible: true
    api_resource_lifecycle_status:
        type: string
        visible: true
    oci_deployment_display_name:
        type: string
        visible: true
    oci_deployment_endpoint:
        type: link
        visible: true
    oci_deployment_backend_routes:
        type: list
        visible: true
outputGroups:
  - title: API Gateway
    outputs:
      - oci_gateway_ocid
      - oci_gateway_display_name
      - oci_gateway_endpoint_type
      - oci_gateway_hostname
  - title: APIs descriptions
    outputs:
      - api_resource_ocid
      - api_resource_specification_type
      - api_resource_lifecycle_status
  - title: Backend Deployments
    outputs:
      - oci_deployment_display_name
      - oci_deployment_endpoint
      - oci_deployment_backend_routes